name: App Shortcut Request
description: Reqeuest a new app shortcut
title: "[New App Shortcut]: "
labels: ["New App Shortcut", "enhancement"]
assignees:
  - PRProd
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to contribute to this project with your requests!
  - type: input
    id: appname
    attributes:
      label: App Name
      description: The name of the app you'd like to see added
      placeholder: ex. YouTube
    validations:
      required: true
  - type: markdown
    attributes:
      value: <br>
  - type: dropdown
    id: platform
    attributes:
      label: Device Platform
      options: 
       - Amazon Fire
       - Apple TV
       - Chromecast
       - Homatics
       - NVIDIA Shield
       - onn.
       - Roku
       - Xiaomi
      multiple: true
      description: The kind of device you own.  You can choose one or more from this list.
    validations:
      required: true
  - type: markdown
    attributes:
      value: <br>
  - type: input
    id: appstoreLink
    attributes:
      label: App Store Link and/or URL to .apk file if sideloaded
      description: Optionally provide a link to the Google Play or Apple store where this app can be downloaded.  If this is a sideloaded app, please include a full URL for where the .apk can be found
    validations:
      required: false
  - type: markdown
    attributes:
      value: "<br>Choose the appropriate link and follow the instructions listed. Paste the results into this **Required Information** box.<br> - [Instructions for Amazon Fire, Chromecast, NVIDIA Shield, and Xiaomi Android devices](https://github.com/PRProd/HA-Firemote/wiki/Providing-Details-for-App-Launcher-Requests#for-fire-tv-chromecast-nvidia-shield-xiaomi-mi-and-other-android-based-devices)<br> - [Instructions for Apple TV Devices](https://github.com/PRProd/HA-Firemote/wiki/Providing-Details-for-App-Launcher-Requests#for-apple-tv-devices)<br> - [Instructions for Roku Devices](https://github.com/PRProd/HA-Firemote/wiki/Providing-Details-for-App-Launcher-Requests#for-roku-devices)"
  - type: textarea
    id: requiredInfo
    attributes:
      label: Required Information
      placeholder: Choose the appropriate link from the list above, follow the directions, and ONLY paste those results into this field
    validations:
      required: true
  - type: markdown
    attributes:
      value: <br>
  - type: textarea
    id: additionalInfo
    attributes:
      label: Optional Comments
      description: Add any additional related comments here, or maybe write something clever like a poem or a joke.
      placeholder: 
    validations:
      required: false
  - type: markdown
    attributes:
      value: <br>Before submitting this issue form, please understand that processing your request may require you to provide some additional information.  By clicking submit, you agree that you will do your best to reply to any communications in a timely manner or your request may be denied.  The more information you provide in this form, and the quicker you respond to communications from me, the faster your request will be added to the Firemote project.
